services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_SQLITE_POOL_SIZE
        value: 2
      - key: N8N_RUNNERS_ENABLED
        value: true
